social/config/routes.rb
Social::Application.routes.draw do
  resources :posts
  resources :friends

  devise_for :users

  resources :users do
    resources :messages
    resources :friends
    resources :posts
  end
  
  root :to => 'posts#index'
  
  

end

social/app/models/friend.rb
class Friend < ActiveRecord::Base
  belongs_to :user
end

social/app/models/message.rb
class Message < ActiveRecord::Base
  
  belongs_to :addressee, :foreign_key => 'destiny_id', :class_name => 'User'
  belongs_to :author, :foreign_key => 'author_id', :class_name => 'User'
  
end

social/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author, :foreign_key => 'user_id', :class_name => 'User'
  
  def self.updates(current_user)
    friends = User.friends(current_user)
    posts = Post.where("user_id IN (?,?)", friends.map(&:id), current_user.id)
  end
  
end

social/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :avatar
  
  after_create :send_mail
  
  has_many :received_messages, :foreign_key => 'destiny_id', :class_name => 'Message'
  has_many :sent_messages, :foreign_key => 'author_id', :class_name => 'Message'
  has_many :friends
  has_many :posts
  
  has_attached_file :avatar, :styles => { :medium => "300x300>" , :thumb => "100x100" }
  
  def avaiable_name
    if self.name.nil? || self.name.empty?
      name = self.email
    else
      name = self.name
    end
  end
  
  def send_mail
    UserMailer.welcome_message(self).deliver
  end
  
  def self.not_friends(current_user)
    friends = Friend.where("user_id = ?", current_user.id)
    if friends.any? 
      users = User.where('id NOT IN (?,?)', friends.map(&:friend_id), current_user.id)
    else 
      User.where("id <> ?", current_user.id) 
    end
  end
  
  def self.friends(current_user)
    friends = User.where("id IN (?)", Friend.where("user_id = ?", current_user.id).map(&:friend_id))
  end
  
  def friend?(current_user)
    Friend.where("user_id = ? AND friend_id = ?", current_user.id, self.id).any?
  end
  
end

social/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

social/app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  
  before_filter :authenticate_user!

  def index
    @users = User.friends(current_user).order('email')
  end

  def create
    @friend = Friend.new
    @friend_id = params[:user_id]
    @friend.friend_id = @friend_id
    @friend.user_id = current_user.id
    respond_to do |format|
      if @friend.save
        format.js
      end
    end
  end

  def destroy
    @friend_id = params[:id]
    @user = User.find(@friend_id)
    @friend = Friend.where("user_id = ? AND friend_id = ?", current_user.id, @friend_id)
    @friend.first.destroy
    respond_to do |format|
      format.js
    end
  end
end

social/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.json
  def create

    @user = User.find(params[:user_id])
    @message = @user.received_messages.build(params[:message])
    @message.author = current_user

    respond_to do |format|
      if @message.save
        format.html { redirect_to @user, :notice => 'Message was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
        format.js
      else
        format.html { render :action => @user }
        format.json { render :json => @message.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to @message, :notice => 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @message.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
      format.js
    end
  end
end

social/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :authenticate_user!

  def index
    @posts = Post.updates(current_user).order('created_at DESC')
    @post = Post.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @posts }
    end
  end

  def create
    @post = Post.new(params[:post])
    @post.user_id = current_user.id
    
    respond_to do |format|
      if @post.save
        format.js
      else
        format.html { render :action => "new" }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, :notice => 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

social/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!
  
  def index
    if(!params[:user].nil? && !params[:user][:name].nil?)
      @query = params[:user][:name]
      words = @query.split(' ').join('%');
      @users = User.where("name LIKE ?", '%' + words + '%')
    else
      @users = User.not_friends(current_user).order('email')
    end
  end
  
  def show
    @user = User.find(params[:id])
    @message = Message.new
  end
  
end

social/app/helpers/application_helper.rb
module ApplicationHelper
  
  def user_header
    if current_user
      link = link_to "Logout", destroy_user_session_url, :method => :delete
      email = current_user.email
      raw "Logged as <em>" + link_to("#{email}", edit_user_registration_path(current_user), :method => :get, :title => 'Update my Profile') + "</em> - #{link}"
    else
      link_to "Login", new_user_session_url
    end
  end
  
end

social/app/helpers/friends_helper.rb
module FriendsHelper
end

social/app/helpers/messages_helper.rb
module MessagesHelper
end

social/app/helpers/posts_helper.rb
module PostsHelper
end

social/app/helpers/users_helper.rb
module UsersHelper
end

social/app/views/friends/_add_friend_again.html.erb
<%= link_to(user_friends_path(@user), :method => :post, :remote => true, :class => "btn btn-mini btn-info add-friend") do %> 	
	<i class="icon-plus icon-white"></i> Add as Friend again
<% end %>

social/app/views/friends/_form.html.erb
<%= form_for(@friend) do |f| %>
  <% if @friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
      <% @friend.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :friend_id %><br />
    <%= f.number_field :friend_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

social/app/views/friends/create.js.erb
var button = '<button class="btn btn-mini friend"><i class="icon-ok"></i> Now You\'re Friends</button>';
$(".add-as-friend-<%= @friend_id %> a.add-friend").fadeOut(300, function(){
    $(this).replaceWith(button);
});

social/app/views/friends/destroy.js.erb
var link = $("<%= escape_javascript(render :partial => 'friends/add_friend_again') %>");

$(".add-as-friend-<%= @friend_id %> a.remove-friend").fadeOut(300, function(){
    $(this).replaceWith(link);
});

social/app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render 'form' %>

<%= link_to 'Show', @friend %> |
<%= link_to 'Back', friends_path %>

social/app/views/friends/index.html.erb
<h1>My Friends List <small>We're friends</small></h1>

<% if(@users.any?) %>
	<p class="lead">
		Cool! You have <%= @users.count %> friend(s) in your friends list. 
		<%= link_to 'Find new friends!', users_path %>
	</p>
<% end %>

<%= render :partial => 'users/listing' %>

social/app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render 'form' %>

<%= link_to 'Back', friends_path %>

social/app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @friend.user_id %>
</p>

<p>
  <b>Friend:</b>
  <%= @friend.friend_id %>
</p>


<%= link_to 'Edit', edit_friend_path(@friend) %> |
<%= link_to 'Back', friends_path %>

social/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My.Social | by Junior Grossi [juniorgro@gmail.com] </title>
  <%= stylesheet_link_tag "styles", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="header">
    <div class="container">
        <div class="logo">
            <a href="<%= root_path %>"></a>
        </div>
        <% if (!current_user.nil?) %>
            <ul>
                <li><a href="<%= root_path %>">Updates</a></li>
                <li><a href="<%= friends_path %>">Friends List</a></li>
                <li><a href="<%= users_path %>">Find New Friends</a></li>
            </ul>
            <div class="search">
                <%= form_for(:user, :url => {:controller => :users, :action => :index}, :method => :get, :html => {:id => 'search-form'}) do |f| %>
                    <%= f.text_field :name, :placeholder => 'Search for friends...' %>
                <% end %>
            </div>
        <% end %>
        <div class="user-header"><%= user_header %></div>
    </div>
</div>

<div class="content">
    <div class="container">
        <% if(!notice.nil?) %>
            <div id="notice" class="alert alert-success"><%= notice %></div>
        <% end %>
        <%= yield %>
    </div>
</div>

<div class="footer">
    <div class="container">
        PUC Minas | &copy; 2012 Junior GROSSI [juniorgro@gmail.com] | DSW7 | Matrícula: 35713
    </div>
</div>

</body>
</html>

social/app/views/messages/_form.html.erb
<%= form_for([@user, @user.received_messages.build], :remote => true) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <h3>New Message</h3>
    <div class="controls">
    	<%= f.text_area :text, :rows => 3, :class => 'span6' %>
    </div>
  </div>
  <%= f.submit 'Send Message', { :class => 'btn btn-primary' } %>

<% end %>

social/app/views/messages/_message.html.erb
<div class="message" id="message_<%= message.id %>">
	<div>
		<%= link_to(user_message_url(@user, message), :method => :delete, :remote => true, :class => 'pull-right', :title => 'Remove') do %>
			<i class="icon-trash"></i>
		<% end %>
		<% if(!message.author.avatar.exists?) %>
			<%= image_tag 'missing.png', :width => 40, :height => 40, :class => 'pull-left' %>
		<% else %>
			<%= image_tag message.author.avatar.url(:thumb), :width => 40, :height => 40, :class => 'pull-left' %>
		<% end %>
		<div class="body">
			<%= link_to message.author.avaiable_name, message.author %>
			<p class="body-data"><%= message.text %></p>
		</div>
	</div>
</div>

social/app/views/messages/create.js.erb
var html = $("<%= escape_javascript(render(:partial => @message)) %>");
$(".messages").append(html.fadeIn(250));
$("#message_text").val('');

social/app/views/messages/destroy.js.erb
$('div#message_' + <%= @message.id %>).slideUp(250);

social/app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

social/app/views/messages/index.html.erb
<h1>Listing messages</h1>

<table>
  <tr>
    <th>Author</th>
    <th>Destiny</th>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @messages.each do |message| %>
  <tr>
    <td><%= message.author_id %></td>
    <td><%= message.destiny_id %></td>
    <td><%= message.text %></td>
    <td><%= link_to 'Show', message %></td>
    <td><%= link_to 'Edit', edit_message_path(message) %></td>
    <td><%= link_to 'Destroy', message, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Message', new_message_path %>

social/app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

social/app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Author:</b>
  <%= @message.author_id %>
</p>

<p>
  <b>Destiny:</b>
  <%= @message.destiny_id %>
</p>

<p>
  <b>Text:</b>
  <%= @message.text %>
</p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

social/app/views/posts/_form.html.erb
<%= form_for(@post, :remote => true, :html => {:class => 'new-post'}) do |f| %>
   	<div class="control-group">
   		<%= f.text_area :body, :rows => 2, :class => 'span6 no-margin', :placeholder => 'What are you thinking now?' %>
   	</div>
    <div class="control-group">
    	<%= f.submit 'Post update', :class => 'btn btn-primary' %>
    </div>
<% end %>

social/app/views/posts/_post.html.erb
<div class="post">
	<% if(!post.author.avatar.exists?) %>
		<%= image_tag 'missing.png', :width => 50, :height => 50, :class => 'pull-left' %>
	<% else %>
		<%= image_tag post.author.avatar.url(:thumb), :width => 50, :height => 50, :class => 'pull-left' %>
	<% end %>
	<div class="body">
		<h3><%= link_to post.author.avaiable_name, post.author %></h3>
		<h4>Posted <%= time_ago_in_words(post.created_at) %> ago</h4>
		<p><%= post.body %></p>
	</div>
</div>

social/app/views/posts/create.js.erb
var post = $("<%= escape_javascript(render(:partial => @post)) %>");
$(".posts").prepend(post.fadeIn(300));
$(".new-post textarea").val('');

social/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

social/app/views/posts/index.html.erb
<h1>Updates</h1>

<%= render :partial => 'form' %>

<div class="posts">
	<% @posts.each do |post| %>
		<%= render :partial => post %>
	<% end %>
</div>

social/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

social/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Body:</b>
  <%= @post.body %>
</p>

<p>
  <b>User:</b>
  <%= @post.user_id %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

social/app/views/users/_form.html.erb
<% form_for @users do |f| %>
	<%= f.label :email, 'E-mail' %>
	<%= f.text_field :email %>
<% end %>

social/app/views/users/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

social/app/views/users/_listing.html.erb
<% if(@users.any?) %>
	<table class="table table-striped users_table">
		<tr>
			<th style="width: 70px">Friend</th>
			<th></th>
			<th>E-mail</th>
			<th>Last Login</th>
			<th>Created</th>
		</tr>

		<% @users.each do |user| %>
			<tr>
				<td>
					<% if(!user.avatar.exists?) %>
						<%= image_tag 'missing.png', :width => 70, :height => 70 %>
					<% else %>
						<%= image_tag user.avatar.url(:thumb), :width => 70, :height => 70 %>
					<% end %>
				</td>
				<td>
					<p><%= link_to user.avaiable_name, user %></p>
					<div class="add-as-friend-<%= user.id %>">
						<% if(!user.friend?(current_user)) %>
							<%= link_to(user_friends_path(user), :method => :post, :remote => true, :class => 'btn btn-mini btn-info add-friend') do %>
								<i class="icon-plus icon-white"></i> Add as Friend
							<% end %>
						<% else %>
							<%= link_to(user_friend_path(current_user, user), :method => :delete, :remote => true, :class => 'btn btn-mini btn-danger remove-friend') do %>
								<i class="icon-minus icon-white"></i> Remove Friend
							<% end %>
						<% end %>
					</div>
				</td>
				<td><%= user.email %></td>
				<td><%= user.last_sign_in_at %></td>
				<td><%= user.created_at %></td>
			</tr>
		<% end %>
	</table>
<% else %>
	<p class="lead">We could't find any user, sorry! <%= link_to 'Try some new friends', users_path %>.</p>
<% end %>
	

social/app/views/users/index.html.erb
<% if(!@query.nil?) %>
	<h1>Searching <small>Let's find new friends!</small></h1>
	<h2>Search results for: <em><%= @query %></em></h2>
<% else %>
	<h1>Find New Friends <small>Who isn't my friend yet?</small></h1>
	<p class="lead">Here there are some interesting friends maybe you want.</p>
<% end %>

<%= render :partial => 'listing' %>

social/app/views/users/show.html.erb
<h1><%= @user.avaiable_name %></h1>

<h2>Messages</h2>

<div class="messages">
	<%= render :partial => 'messages/message', :collection => @user.received_messages %>
</div>

<%= render :partial => 'messages/form' %>